### ISSUE TITLE
Class CHtml not found

### ISSUE THREAD

**Issue by asyd** [WASasquatch/humhub-themes-hivehub#1]
Hello,

using humhub 0.20.0, when switching to HiveHub theme, I have the following error:

`
PHP message: PHP Fatal error:  Class 'CHtml' not found in /srv/humhub/humhub-0.20.0/themes/HiveHub/views/layouts/main.php on line 7
`

**Comment by daglex** [comment]
The template is not adapted to the version 0.20.0

**Comment by ghost** [comment]
and for version 1.0.0 ?

**Comment by MVprobr** [comment]
Same error at Yii Framework/2.0.8 and HumHub 1.0.1

waiting for news.

**Comment by rjantoine** [comment]
This was coded for Yii 1.1. It's not a simple "bug" fix but would need to be rewritten to use the new classes, etc.
